-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: AspaklaryaLockDown/dbPatches/bad_words.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bad_words (
  bw_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  bw_word VARBINARY(255) NOT NULL,
  bw_dont_start_with VARBINARY(255) NOT NULL,
  bw_dont_end_with VARBINARY(255) NOT NULL,
  UNIQUE INDEX bw_word (bw_word),
  UNIQUE INDEX bw_id (bw_id),
  PRIMARY KEY(bw_id, bw_word)
) /*$wgDBTableOptions*/;
