-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: AspaklaryaLockDown/dbPatches/ptches/pages_add_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/aspaklarya_lockdown_pages
ADD  al_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
DROP  PRIMARY KEY,
ADD  PRIMARY KEY (al_id);
CREATE UNIQUE INDEX al_id ON  /*_*/aspaklarya_lockdown_pages (al_id);