-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: AspaklaryaLockDown/dbPatches/ptches/revisions_add_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX al_rev_id ON  /*_*/aspaklarya_lockdown_revisions;
DROP  INDEX al_page_id ON  /*_*/aspaklarya_lockdown_revisions;
ALTER TABLE  /*_*/aspaklarya_lockdown_revisions
ADD  alr_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
ADD  alr_rev_id INT UNSIGNED NOT NULL,
ADD  alr_page_id INT UNSIGNED NOT NULL,
DROP  al_rev_id,
DROP  al_page_id,
DROP  PRIMARY KEY,
ADD  PRIMARY KEY (alr_id, alr_rev_id);
CREATE UNIQUE INDEX alr_id ON  /*_*/aspaklarya_lockdown_revisions (alr_id);
CREATE UNIQUE INDEX alr_rev_id ON  /*_*/aspaklarya_lockdown_revisions (alr_rev_id);
CREATE UNIQUE INDEX alr_page_id ON  /*_*/aspaklarya_lockdown_revisions (alr_rev_id, alr_page_id);