-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: AspaklaryaLockDown/dbPatches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/aspaklarya_lockdown_pages (
  al_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  al_page_id INT UNSIGNED NOT NULL,
  al_read_allowed TINYINT(1) UNSIGNED DEFAULT 1 NOT NULL,
  UNIQUE INDEX al_id (al_id),
  UNIQUE INDEX al_page_id (al_page_id),
  PRIMARY KEY(al_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/aspaklarya_lockdown_create_titles (
  al_page_title VARBINARY(255) NOT NULL,
  al_page_namespace INT NOT NULL,
  al_lock_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  UNIQUE INDEX al_lock_id (al_lock_id),
  UNIQUE INDEX al_page_name (
    al_page_title, al_page_namespace
  ),
  PRIMARY KEY(
    al_lock_id, al_page_title, al_page_namespace
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/aspaklarya_lockdown_revisions (
  al_rev_id INT UNSIGNED NOT NULL,
  al_page_id INT UNSIGNED NOT NULL,
  UNIQUE INDEX al_rev_id (al_rev_id),
  UNIQUE INDEX al_page_id (al_rev_id, al_page_id),
  PRIMARY KEY(al_rev_id)
) /*$wgDBTableOptions*/;
