-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: PageLockdown/dbPatches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/page_lockdown_pages (
  pl_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  pl_page_id INT UNSIGNED NOT NULL,
  pl_level TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  UNIQUE INDEX pl_id (pl_id),
  UNIQUE INDEX pl_page_id (pl_page_id),
  PRIMARY KEY(pl_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/page_lockdown_create_titles (
  plt_page_title VARBINARY(255) NOT NULL,
  plt_page_namespace INT NOT NULL,
  plt_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  UNIQUE INDEX plt_id (plt_id),
  UNIQUE INDEX plt_page_name (
    plt_page_title, plt_page_namespace
  ),
  PRIMARY KEY(
    plt_id, plt_page_title, plt_page_namespace
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/page_lockdown_revisions (
  plr_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  plr_rev_id INT UNSIGNED NOT NULL,
  plr_page_id INT UNSIGNED NOT NULL,
  UNIQUE INDEX plr_id (plr_id),
  UNIQUE INDEX plr_rev_id (plr_rev_id),
  UNIQUE INDEX plr_page_id (plr_rev_id, plr_page_id),
  PRIMARY KEY(plr_id, plr_rev_id)
) /*$wgDBTableOptions*/;
