-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: AspaklaryaLockDown/dbPatches/bad_words.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bad_words (
  bw_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  bw_word BLOB NOT NULL, bw_dont_start_with BLOB NOT NULL,
  bw_dont_end_with BLOB NOT NULL
);

CREATE UNIQUE INDEX bw_word ON /*_*/bad_words (bw_word);

CREATE UNIQUE INDEX bw_id ON /*_*/bad_words (bw_id);
