-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: AspaklaryaLockDown/dbPatches/ptches/pages_add_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__aspaklarya_lockdown_pages AS
SELECT  al_page_id,  al_read_allowed
FROM  /*_*/aspaklarya_lockdown_pages;
DROP  TABLE  /*_*/aspaklarya_lockdown_pages;
CREATE TABLE  /*_*/aspaklarya_lockdown_pages (    al_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,    al_page_id INTEGER UNSIGNED NOT NULL,    al_read_allowed SMALLINT UNSIGNED DEFAULT 1 NOT NULL  );
INSERT INTO  /*_*/aspaklarya_lockdown_pages (al_page_id, al_read_allowed)
SELECT  al_page_id,  al_read_allowed
FROM  /*_*/__temp__aspaklarya_lockdown_pages;
DROP  TABLE /*_*/__temp__aspaklarya_lockdown_pages;
CREATE UNIQUE INDEX al_page_id ON  /*_*/aspaklarya_lockdown_pages (al_page_id);
CREATE UNIQUE INDEX al_id ON  /*_*/aspaklarya_lockdown_pages (al_id);