-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: AspaklaryaLockDown/dbPatches/ptches/revisions_add_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__aspaklarya_lockdown_revisions AS
SELECT
FROM  /*_*/aspaklarya_lockdown_revisions;
DROP  TABLE  /*_*/aspaklarya_lockdown_revisions;
CREATE TABLE  /*_*/aspaklarya_lockdown_revisions (    alr_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,    alr_rev_id INTEGER UNSIGNED NOT NULL,    alr_page_id INTEGER UNSIGNED NOT NULL  );
INSERT INTO  /*_*/aspaklarya_lockdown_revisions ()
SELECT
FROM  /*_*/__temp__aspaklarya_lockdown_revisions;
DROP  TABLE /*_*/__temp__aspaklarya_lockdown_revisions;
CREATE UNIQUE INDEX alr_id ON  /*_*/aspaklarya_lockdown_revisions (alr_id);
CREATE UNIQUE INDEX alr_rev_id ON  /*_*/aspaklarya_lockdown_revisions (alr_rev_id);
CREATE UNIQUE INDEX alr_page_id ON  /*_*/aspaklarya_lockdown_revisions (alr_rev_id, alr_page_id);