-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: AspaklaryaLockDown/dbPatches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/aspaklarya_lockdown_pages (
  al_page_id INTEGER UNSIGNED NOT NULL,
  al_read_allowed SMALLINT UNSIGNED DEFAULT 1 NOT NULL,
  PRIMARY KEY(al_page_id)
);

CREATE UNIQUE INDEX al_page_id ON /*_*/aspaklarya_lockdown_pages (al_page_id);


CREATE TABLE /*_*/aspaklarya_lockdown_logs (
  al_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  al_page_id INTEGER UNSIGNED NOT NULL,
  al_user_id INTEGER UNSIGNED NOT NULL,
  al_action VARCHAR(255) NOT NULL,
  al_date BLOB DEFAULT '19700101000000' NOT NULL,
  al_comment VARCHAR(255) NOT NULL,
  al_page_name VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX al_id ON /*_*/aspaklarya_lockdown_logs (al_id);

CREATE INDEX al_page_id ON /*_*/aspaklarya_lockdown_logs (al_page_id);

CREATE INDEX al_user_id ON /*_*/aspaklarya_lockdown_logs (al_user_id);

CREATE INDEX al_date ON /*_*/aspaklarya_lockdown_logs (al_date);

CREATE INDEX al_page_name ON /*_*/aspaklarya_lockdown_logs (al_page_name);


CREATE TABLE /*_*/aspaklarya_lockdown_create_pages (
  al_page_name VARCHAR(255) NOT NULL,
  al_lock_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);

CREATE UNIQUE INDEX al_lock_id ON /*_*/aspaklarya_lockdown_create_pages (al_lock_id);

CREATE UNIQUE INDEX al_page_name ON /*_*/aspaklarya_lockdown_create_pages (al_page_name);
