-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: AspaklaryaLockDown/dbPatches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/aspaklarya_lockdown_pages (
  al_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  al_page_id INTEGER UNSIGNED NOT NULL,
  al_read_allowed SMALLINT UNSIGNED DEFAULT 1 NOT NULL
);

CREATE UNIQUE INDEX al_id ON /*_*/aspaklarya_lockdown_pages (al_id);

CREATE UNIQUE INDEX al_page_id ON /*_*/aspaklarya_lockdown_pages (al_page_id);


CREATE TABLE /*_*/aspaklarya_lockdown_create_titles (
  al_page_title BLOB NOT NULL, al_page_namespace INTEGER NOT NULL,
  al_lock_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);

CREATE UNIQUE INDEX al_lock_id ON /*_*/aspaklarya_lockdown_create_titles (al_lock_id);

CREATE UNIQUE INDEX al_page_name ON /*_*/aspaklarya_lockdown_create_titles (
  al_page_title, al_page_namespace
);


CREATE TABLE /*_*/aspaklarya_lockdown_revisions (
  alr_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  alr_rev_id INTEGER UNSIGNED NOT NULL,
  alr_page_id INTEGER UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX alr_id ON /*_*/aspaklarya_lockdown_revisions (alr_id);

CREATE UNIQUE INDEX alr_rev_id ON /*_*/aspaklarya_lockdown_revisions (alr_rev_id);

CREATE UNIQUE INDEX alr_page_id ON /*_*/aspaklarya_lockdown_revisions (alr_rev_id, alr_page_id);
