-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: AspaklaryaLockdown/dbPatches/add_level_field.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  aspaklarya_lockdown_pages
ADD  al_level SMALLINT DEFAULT 0 NOT NULL;