-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: AspaklaryaLockDown/dbPatches/bad_words.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bad_words (
  bw_id SERIAL NOT NULL,
  bw_word TEXT NOT NULL,
  bw_dont_start_with TEXT NOT NULL,
  bw_dont_end_with TEXT NOT NULL,
  PRIMARY KEY(bw_id, bw_word)
);

CREATE UNIQUE INDEX bw_word ON bad_words (bw_word);

CREATE UNIQUE INDEX bw_id ON bad_words (bw_id);
