-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: AspaklaryaLockDown/dbPatches/ptches/pages_add_id.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX "primary";
ALTER TABLE  aspaklarya_lockdown_pages
ADD  al_id SERIAL NOT NULL;
CREATE UNIQUE INDEX al_id ON aspaklarya_lockdown_pages (al_id);
ALTER TABLE  aspaklarya_lockdown_pages
ADD  PRIMARY KEY (al_id);