-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: AspaklaryaLockdown/dbPatches/remove_read_allowed_field.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  aspaklarya_lockdown_pages
DROP  al_read_allowed;