-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: AspaklaryaLockDown/dbPatches/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE aspaklarya_lockdown_pages (
  al_id SERIAL NOT NULL,
  al_page_id INT NOT NULL,
  al_read_allowed SMALLINT DEFAULT 1 NOT NULL,
  PRIMARY KEY(al_id)
);

CREATE UNIQUE INDEX al_id ON aspaklarya_lockdown_pages (al_id);

CREATE UNIQUE INDEX al_page_id ON aspaklarya_lockdown_pages (al_page_id);


CREATE TABLE aspaklarya_lockdown_create_titles (
  al_page_title TEXT NOT NULL,
  al_page_namespace INT NOT NULL,
  al_lock_id SERIAL NOT NULL,
  PRIMARY KEY(
    al_lock_id, al_page_title, al_page_namespace
  )
);

CREATE UNIQUE INDEX al_lock_id ON aspaklarya_lockdown_create_titles (al_lock_id);

CREATE UNIQUE INDEX al_page_name ON aspaklarya_lockdown_create_titles (
  al_page_title, al_page_namespace
);


CREATE TABLE aspaklarya_lockdown_revisions (
  alr_id SERIAL NOT NULL,
  alr_rev_id INT NOT NULL,
  alr_page_id INT NOT NULL,
  PRIMARY KEY(alr_id, alr_rev_id)
);

CREATE UNIQUE INDEX alr_id ON aspaklarya_lockdown_revisions (alr_id);

CREATE UNIQUE INDEX alr_rev_id ON aspaklarya_lockdown_revisions (alr_rev_id);

CREATE UNIQUE INDEX alr_page_id ON aspaklarya_lockdown_revisions (alr_rev_id, alr_page_id);
